url_room = 'https://api-edu.skysmart.ru/api/v1/task/preview'
url_auth = 'https://id.skyeng.ru/login?skin=skysmart-class&redirect=https%3A%2F%2Fedu.skysmart.ru%2Fstudent&registration=https%3A%2F%2Fedu.skysmart.ru%2Fregistration-student'
url_steps = 'https://api-edu.skysmart.ru/api/v1/content/step/load?stepUuid='
url_room_preview = 'https://api-edu.skysmart.ru/api/v1/task/preview'
url_auth2 = 'https://api-edu.skysmart.ru/api/v1/user/registration/teacher'
